# SPDX-License-Identifier: MIT
namespace: danmwallace
name: hermes
version: 1.2.1
readme: README.md
authors:
  - Dan Wallace <dan.m.wallace@gmail.com>
description: Deploy Hermes AI agent and Gateway as Podman Quadlets, or natively on Fedora Server.
license:
  - MIT
tags:
  - linux
  - infrastructure
  - podman
  - hermes
  - ai
dependencies:
  containers.podman: ">=1.11.0"
  ansible.posix: ">=1.5.0"
  community.general: ">=8.0.0"
repository: https://github.com/danmwallace/ansible-collection-hermes
documentation: https://github.com/danmwallace/ansible-collection-hermes
homepage: https://github.com/danmwallace/ansible-collection-hermes
issues: https://github.com/danmwallace/ansible-collection-hermes/issues
build_ignore: []
