---
- name: Destroy molecule instance
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove hermes-ostree container
      containers.podman.podman_container:
        name: hermes-ostree
        state: absent
