---
dependency:
  name: galaxy
ansible:
  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --inventory=${MOLECULE_SCENARIO_DIRECTORY}/inventory/hosts.yml
scenario:
  test_sequence:
    - dependency
    - destroy
    - create
    - converge
    - verify
    - destroy
