---
dependency:
  name: galaxy
provisioner:
  name: ansible
  options:
    skip-tags: molecule-notest,notest
  inventory:
    hosts:
      all:
        hosts:
          hermes-gateway-instance:
            ansible_connection: containers.podman.podman
scenario:
  test_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
