---
# SPDX-License-Identifier: MIT
galaxy_info:
  role_name: hermes
  namespace: danmwallace
  author: Dan Wallace
  description: Deploy Hermes Agent Docker Compose stack behind Traefik.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - docker
    - hermes
    - ai
    - agent
    - traefik

dependencies: []
